// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/aaasaasa/:route': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/aaasaasa/[route]').default>>>>
    }
    '/api/ingest': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ingest.post').default>>>>
    }
    '/api/qdrant/ping': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/qdrant/ping.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/nuxt@4.0.3_@parcel+watcher@2.5.1_@types+node@24.3.0_@vue+compiler-sfc@3.5.21_db0@0.3.2__a2b481e42048dca7f4fef2bc37ce4455/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}